---
- name: Install Firewalld
  package:
    name: firewalld
    state: latest
  become: true
  become_user: root

- name: Import ports variable
  include_vars: main.yaml

- name: Select ports
  set_fact:
    ports: |-
      {{
        (ports['loadbalancer'] if ansible_host in groups['loadbalancer'] else [])
        + (ports['master'] if ansible_host in groups['master'] else [])
        + (ports['worker'] if ansible_host in groups['worker'] else [])
      }}

- name: Configure Firewalld
  template:
    src: firewalld.j2
    dest: /etc/firewalld/services/kubernetes.xml
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root

- name: Reload Firewalld
  service:
    name: firewalld
    state: reloaded
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
