---
- name: Cover CentOS edge cases
  include_tasks: centos.yaml
  when: ansible_facts['distribution'] == 'CentOS'

- name: Update system
  package:
    name: "*"
    state: latest
  register: update
  become: true
  become_user: root

- name: Restart if package updated
  reboot:
    connect_timeout: 5
    reboot_timeout: 300
    reboot_timeout: 300
    msg: "Reboot initiated by Ansible for package updates."
  when: update is changed
  become: true
  become_user: root
