---
- name: Cover CentOS edge cases
  include_tasks: update/centos.yaml
  when: ansible_facts['distribution'] == 'CentOS'

- name: Update system
  package:
    name: "*"
    state: latest
  register: update
  become: true
  become_user: root

- name: Restart if package updated
  reboot: {}
  when: update is changed
  become: true
  become_user: root
