---
- name: Enable sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl }}"
  tags: sysctl
  become: true
  become_user: root

- name: Configure sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  tags: sysctl
  become: true
  become_user: root
